### ISSUE TITLE
Modifying a repository secret

### ISSUE THREAD

**Issue by JKRhb** [eclipse-thingweb/.eclipsefdn#18]
Hi there :)

For [dart_wot](https://github.com/eclipse-thingweb/dart_wot) and other repositories, we are using codecov for displaying code coverage information. Recently, I noticed that the `CODECOV_TOKEN` secret that was defined before moving dart_wot to the Thingweb organization apparently hasn't been updated – or rather: there is now only a sequence of stars in the otterdog configuration file, supposedly indicating that it existed before:

https://github.com/eclipse-thingweb/.eclipsefdn/blob/bb339a27576a857cf1b98c121563592f1e17448b/otterdog/eclipse-thingweb.jsonnet#L55-L59

What would be the process of updating this secret? Apparently, if there is no (valid?) token defined, you get rate-limited at some point, so adding it back to the repository would be a nice thing to have, I think.

**Comment by JKRhb** [comment]
After checking for the secret via https://github.com/eclipse-thingweb/dart_wot/pull/146, I've noticed the `CODECOV_TOKEN` is in fact still defined, but points to the repository's previous organization on codecov. Therefore, a new token needs to be provided to make proper use of the code coverage metric again.

**Comment by netomi** [comment]
Can you share the token for the new org via the mechanism explained here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Sharing-secrets ?

**Comment by JKRhb** [comment]
> Can you share the token for the new org via the mechanism explained here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Sharing-secrets ?

Thank you! I've sent you the token via Matrix, as described on the Wiki page.

**Comment by netomi** [comment]
Created #20 .

**Comment by JKRhb** [comment]
Thank you! Everything now works as expected again :)
