### ISSUE TITLE
Setting the Thingweb logo as the avatar of the `eclipse-thingweb-bot`

### ISSUE THREAD

**Issue by JKRhb** [eclipse-thingweb/.eclipsefdn#30]
To give the eclipse-thingweb-bot a more "official" look (e.g., when making releases on behalve of the project team), it would be great if the Thingweb logo could be set as its avatar. This has a very low priority, though :)

**Comment by netomi** [comment]
Changed to the project logo:

![image](https://github.com/user-attachments/assets/ea272c15-3896-4924-b9e5-8a34a7ac74b0)

**Comment by JKRhb** [comment]
> Changed to the project logo:

Awesome, thank you very much! :)
