### ISSUE TITLE
Adding homepage of this repo

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/.eclipsefdn#4]
I have realized at #3 that we have https://eclipse-thingweb.github.io/.eclipsefdn/ . @netomi can we add it as "homepage" of this repo? Also, does this repo need its own config?

**Comment by netomi** [comment]
This repo is part of the default config: https://github.com/EclipseFdn/otterdog-defaults/blob/main/otterdog-defaults.libsonnet#L236

it is automatically created when we enable self service for an organization.
Adding the mentioned page as homepage makes sense, will add it.

**Comment by netomi** [comment]
I have now added the homepage definition to the default and synced all .eclipsefdn repos.

**Comment by egekorkan** [comment]
Thanks!
